---
ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff
        args:
          - --fix
          # ignore: E501 Line too long
          - --ignore=E501
          # ignore: N999 Invalid module name: 'Application'
          - --ignore=N999
      - id: ruff-format

  # Security linter
  - repo: https://github.com/pycqa/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        name: bandit
        exclude: tests/
