---
ci:
  autoupdate_schedule: monthly
  skip:
    - pylint
    - pytest

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort
        args:
          - --line-length=79
          - --profile=black

  # Remove unused imports, variables, statements
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake

  # Auto-update syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args:
          - --py311-plus

  # Linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args:
          # ignore: E501 Line too long
          - --ignore=E501
      - id: ruff-format

  # Security linter
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        name: bandit
        exclude: tests/

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types_or: [python]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: env QT_QPA_PLATFORM=minimal poetry run pytest
        language: system
        types_or: [python]
        pass_filenames: false
        always_run: true
        args:
          - --cov-reset
          - --cov-config=.coveragerc
          - --cov=infinitecopy
          - --cov-report=term
