---
ci:
  skip:
    - pylint
    - pytest

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
        args:
          - --line-length=79

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args:
          - --line-length=79
          - --profile=black

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit
        exclude: tests/

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types_or: [python]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: env QT_QPA_PLATFORM=minimal poetry run pytest
        language: system
        types_or: [python]
        pass_filenames: false
        always_run: true
        args:
          - --cov-reset
          - --cov-config=.coveragerc
          - --cov=infinitecopy
          - --cov-report=term
